TicketSystemNew/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('TicketUser/', include('TicketUser.urls'), name='TicketUser'),
    path('', include('TicketUser.urls'), name='TicketUser'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TicketUser/urls.py
from django.urls import path
from .views import *

app_name = 'TicketUser'

urlpatterns = [
    path('', user_login, name='home'),

    path('login/', user_login, name='user_login'),
    path('user_logout/', user_logout, name='user_logout'),
    path('user_dashboard/', user_dashboard, name='user_dashboard'),
    path('agent_dashboard/', agent_dashboard, name='agent_dashboard'),
    path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
    path('create_ticket/', create_ticket, name='create_ticket'),
    path('ticket_list/', ticket_list, name='ticket_list'),
    path('admin_action/<id>', admin_action, name='admin_action'),
    path('agent_action/<id>', agent_action, name='agent_action'),
    path('reopen/<id>', reopen, name='reopen'),
    path('user_view_ticket/<id>', user_view_ticket, name='user_view_ticket'),
    path('agent_view_ticket/<id>', agent_view_ticket, name='agent_view_ticket'),
    path('admin_view_ticket/<id>', admin_view_ticket, name='admin_view_ticket'),
    path('close_ticket/<id>', close_ticket, name='close_ticket'),
    path('attended_view/<id>', attended_view, name='attended_view'),
]

TicketUser/forms.py
from .models import *
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.EmailField(max_length=60, required=True, widget=forms.EmailInput(
        attrs={'class': 'form-control', 'id': 'inputEmail', 'placeholder': 'Enter Email', 'autocomplete': 'off'}))

    password = forms.CharField(required=True, strip=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'id': 'inputPassword', 'placeholder': 'Enter Password', 'name': 'password'}))


# Ticket details
class Ticket_Form(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = [
          'ticket_title','ticket_desc','ticket_user_uploaded_document','organization_name',
          'organization_website_url','organization_category','ticket_related_area',
          'ticket_technology_stack','technical_person_name','technical_person_email',
          'technical_person_contact_number'
          ]
        
        
# admin Action details
class AdminActionForm(forms.Form):
    agent_id = forms.ModelChoiceField(queryset=Agent.objects.all())
    admin_to_agent_remark = forms.CharField(required=False)
        
        
# Agent Action details
class AgentActionForm(forms.Form):
    agent_to_admin_remark = forms.CharField(widget=forms.Textarea, required=False)
    agent_to_user_remark = forms.CharField(widget=forms.Textarea, required=False)
    agent_ticket_upload_document = forms.FileField(required=False)
    agent_action = forms.ModelChoiceField(queryset=TicketStatus.objects.all())
        
        
# reopen details
class ReopnForm(forms.Form):
    user_ticket_reopen_data_description = forms.CharField(widget=forms.Textarea)
    user_ticket_reopen_docs = forms.FileField(required=False)

        

TicketUser/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import authenticate, login, logout
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .utils import *

# Create your views here.
def home(request):
  return render(request, 'TicketUser/home.html')


@login_required()
def user_dashboard(request):
  data = Ticket.objects.filter(ticket_raised_by=request.user)
  return render(request, 'TicketUser/user_dashboard.html', {'data': data})


@login_required()
def agent_dashboard(request):
  data = AdminAction.objects.filter(agent_id__user_id=request.user)
  # ticket_data = []
  # for tickets in data:
  #   Ticket.objects.get(tickets.ticket_id)
    
  return render(request, 'TicketUser/agent_dashboard.html', {'data': data})


@login_required()
def admin_dashboard(request):
  data = Ticket.objects.all()
  return render(request, 'TicketUser/admin_dashboard.html', {'data': data})


def user_login(request):
  print("in login view")

  if request.method == 'POST':
    form = LoginForm(request.POST)
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    
    print("User ", user)
    if user:
      user_role = UserRoleMapping.objects.get(user_id=user)
      print("role ", user_role.role_name)
      
      login(request, user)
      
      if user_role.role_name == 'agent':
        return redirect('TicketUser:agent_dashboard')
      elif user_role.role_name == 'user':
        return redirect('TicketUser:user_dashboard')
      else:
        return redirect('TicketUser:admin_dashboard')
    else:
      print("no user found")
      messages.error(request, "Incorrect login credentials", extra_tags="danger")
  else:
    form = LoginForm()
  return render(request, 'TicketUser/user_login.html', {'form':form})


@login_required()
def user_logout(request):
  logout(request)
  
  return redirect("TicketUser:user_login")


@login_required()
def create_ticket(request):
  
  if request.method == 'POST':
    form = Ticket_Form(request.POST, request.FILES)
    if form.is_valid():
    
      temp_obj = form.save(commit=False)
      # update 
      # ticket_reference_number
      # ticket_raised_by
      # ticket_status
      # generate ticket ID
      
      TKT_ID = generate_TKT_ID()
      while Ticket.objects.filter(ticket_reference_number=TKT_ID).exists():
          print("exists and ticket ", TKT_ID)
          TKT_ID = generate_TKT_ID()
      print("Generated Ticket number ", TKT_ID)
      
      ticket_status_pending_obj = TicketStatus.objects.get(
            status='open')
      
      temp_obj.ticket_reference_number = TKT_ID
      temp_obj.ticket_raised_by = request.user
      temp_obj.ticket_status = ticket_status_pending_obj
      
      temp_obj.save()
      form.save_m2m()
      messages.success(request, "Ticket Added Successfully", extra_tags='success')
    else:
      messages.success(request, "Invalid Data", extra_tags='danger')
  
  else:
    form = Ticket_Form()

  
  return render(request, 'TicketUser/create_ticket.html', {'form':form})


@login_required()
def ticket_list(request):

  
  return render(request, 'TicketUser/ticket_list.html')


@login_required()
def admin_action(request, id):
  ticket_obj = Ticket.objects.get(id=id)
  if request.method == 'POST':
    form = AdminActionForm(request.POST, request.FILES)
    
    if form.is_valid():
      ticket_data = Ticket.objects.get(id=id)
      
      if ticket_data.ticket_status.status == 'open' or ticket_data.ticket_status.status == 'escalated':
        agent_id = request.POST.get('agent_id')
        admin_to_agent_remark = request.POST.get('admin_to_agent_remark')
        
        admin_action = AdminAction.objects.create(ticket_id=ticket_obj, agent_id=Agent.objects.get(id=agent_id), admin_to_agent_remark=admin_to_agent_remark)
        admin_action.save()
        
        ticket_status_pending_obj = TicketStatus.objects.get(status='assigned')
        ticket_data.ticket_status = ticket_status_pending_obj
        ticket_data.save()
        messages.success(request, "Admin assigned ticket to agent", extra_tags='success')
      else:
        messages.success(request, "Already assigned", extra_tags='danger')
    else:
      messages.success(request, "Invalid Data", extra_tags='danger')
  else:
    agent_list = Agent.objects.all()
    form = AdminActionForm(initial={'agent_id': agent_list})
  
  return render(request, 'TicketUser/admin_action.html', {'form': form, 'ticket_obj': ticket_obj})


# No USE
@login_required()
def agent_action(request, id):
  ticket_details = Ticket.objects.get(id=id)
  user = request.user
  agent_details = Agent.objects.get(user_id=user)
  
  if request.method == 'POST':
    form = AgentActionForm(request.POST, request.FILES)
    
    if form.is_valid():
      form.save()
      
      status_selected = request.POST.get('agent_action')
      print("action ", status_selected)
      
      # update ticket status for user
      ticket_data = Ticket.objects.get(id=id)
      ticket_status_pending_obj = TicketStatus.objects.get(id=status_selected)
      ticket_data.ticket_status = ticket_status_pending_obj
      ticket_data.save()
      
      # update ticket status for agent
      admin_action = AdminAction.objects.get(ticket_id=id, agent_id=agent_details)
      ticket_status_pending_obj = TicketStatus.objects.get(id=status_selected)
      admin_action.ticket_status_to_agent = ticket_status_pending_obj
      admin_action.save()
      
      messages.success(request, "Agent response given", extra_tags='success')
    else:
      messages.success(request, "Invalid Data", extra_tags='danger')
    
    
  else:
    form = AgentActionForm(initial={'ticket_id':ticket_details, 'agent_id':agent_details})
  
  return render(request, 'TicketUser/agent_action.html', {'form': form, 'ticket_details': ticket_details})


@login_required()
def reopen(request, id):
  ticket_details = Ticket.objects.get(id=id)
  
  if ticket_details.ticket_status.status == 'resolved' or ticket_details.ticket_status.status == 'insufficient data':
  
    if request.method == 'POST':
      form = ReopnForm(request.POST,  request.FILES)
      
      if form.is_valid():
        user_ticket_reopen_data_description = request.POST.get('user_ticket_reopen_data_description')
        user_ticket_reopen_docs = request.POST.get('user_ticket_reopen_docs')
        
        if ticket_details.ticket_status.status == 'insufficient data':
          new_status = 'data provided'
        else:
          new_status = 'reopen'
          
        reopen_obj = Reopen.objects.create(
          ticket_id=ticket_details,
          user_ticket_reopen_data_description=user_ticket_reopen_data_description,
          user_ticket_reopen_docs=user_ticket_reopen_docs,
          user_ticket_action_on_agent_response=TicketStatus.objects.get(status=new_status),
          agent_action_id=AgentAction.objects.filter(ticket_id=ticket_details).last()
        )
        reopen_obj.save()
        
        # update  ticket status for user
        ticket_data = Ticket.objects.get(id=id)
        ticket_status_pending_obj = TicketStatus.objects.get(status=new_status)
        ticket_data.ticket_status = ticket_status_pending_obj
        ticket_data.save()
        
        messages.success(request, "Reopen data submitted", extra_tags='success')
        return redirect('TicketUser:user_view_ticket', id=id)
      else:
        messages.success(request, "Invalid Data", extra_tags='danger')
    else:
      form = ReopnForm()
  else:
    messages.success(request, "Ticket can not be reopen", extra_tags='danger')
    return redirect('TicketUser:user_view_ticket', id=ticket_details.id)
    

  
  return render(request, 'TicketUser/reopen.html', {'form': form, 'ticket_details': ticket_details})


@login_required()
def admin_view_ticket(request, id):
  
  ticket_details = Ticket.objects.get(id=id)
  print(ticket_details)
  
  # agent = Agent.objects.get(user_id=request.user)
  admin_action = AdminAction.objects.filter(ticket_id=id).last()
  agent_resp = AgentAction.objects.filter(ticket_id=id)
  
  
  all_data = []
  for resp in agent_resp:
    if resp.agent_action.status == 'attending':
      all_data.append({"agent_resp": resp})
    else:
      agent_response = AgentResponse.objects.get(agent_action_id=resp.id)
      user_resp = Reopen.objects.filter(agent_action_id=resp.id)
      if user_resp:
        print("user resp found")
        all_data.append({"agent_action": resp, "agent_resp": agent_response, 'user_resp': user_resp[0]})
      else:
        print('no user resp[]')
        all_data.append({"agent_action": resp, "agent_resp": agent_response,})
  
  # all_data = []
  # for resp in agent_resp:
  #   user_resp = Reopen.objects.filter(agent_action_id=resp.id)
  #   if user_resp:
  #     all_data.append({"agent_resp": resp, 'user_resp': user_resp[0]})
  #   else:
  #     all_data.append({"agent_resp": resp})
  
  print(all_data)
    
  
  return render(request, 'TicketUser/admin_view_ticket.html', {"ticket_data": ticket_details, 'data': all_data, 'admin_action': admin_action})


@login_required()
def agent_view_ticket(request, id):

      
  if request.method == 'POST':
    form = AgentActionForm(request.POST, request.FILES)
    
    if form.is_valid():
      agent_to_admin_remark = request.POST.get('agent_to_admin_remark')
      agent_to_user_remark = request.POST.get('agent_to_user_remark')
      agent_ticket_upload_document = request.POST.get('agent_ticket_upload_document')
      agent_action_id = request.POST.get('agent_action')
      
      print("action ", agent_action_id)
      
      ticket_details = Ticket.objects.get(id=id)
      agent_details = Agent.objects.get(user_id=request.user)
      
      if ticket_details.ticket_status.status != 'attending':
        messages.error(request, "Please attend ticket first", extra_tags='danger')

TicketUser/templates/TicketUser/admin_action.html
{% extends 'TicketUser/base.html' %}

{% block admin_action %}

<div class="container mt-5">
  <h3 class="text-center">Admin Action</h3>

  <div class="row justify-content-md-center my-2">
    {% if messages %}
      {% for message in messages %}
          <div class="fw-semibold alert alert-{{message.extra_tags}}">{{message}}</div>
      {% endfor %}
    {% endif %}
  </div>

  <form method='POST' novalidate>
    {% csrf_token %}
    <div class="mb-3">
      <label for="ticket_title" class="form-label">Ticket ID:</label>
      {{ticket_obj.ticket_reference_number}}
    </div>
    <div class="mb-3">
      <label for="ticket_desc" class="form-label">Select Agent:</label>
      {{form.agent_id}}
    </div>
    <div class="mb-3">
      <label for="organization_name" class="form-label">Admin Remark to agent:</label>
      {{form.admin_to_agent_remark}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock %}

TicketUser/templates/TicketUser/admin_dashboard.html
{% extends 'TicketUser/base.html' %}

{% block admin_dashboard %}
<div>
  <h3 class='text-senter'>Ticket List</h3>
    
  <table class="table">
    <thead>
      <tr>
        <th scope="col">s.No.</th>
        <th scope="col">Ticket Number</th>
        <th scope="col">Ticket title</th>
        <th scope="col">Ticket Status</th>
        <th scope="col">Action</th>
        <th scope="col">View Details</th>
      </tr>
    </thead>
    <tbody>
      {% for d in data %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{d.ticket_reference_number}}</td>
        <td>{{d.ticket_title}}</td>
        <td>{{d.ticket_status}}</td>
        {% if d.ticket_status.status == 'closed' %}
        <td>Closed</td>
        {% elif d.ticket_status.status == 'open' %}
        <td><a href="{% url 'TicketUser:admin_action' d.id %}">Assign Ticket</a></td>
        {% else %}
        <td>-----</td>
        {% endif %}
        <td><a href="{% url 'TicketUser:admin_view_ticket' d.id %}">View</a></td>
        
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

TicketUser/templates/TicketUser/admin_view_ticket.html
{% extends 'TicketUser/base.html' %}

{% block admin_view_ticket %}

<div class="my-3">
  <h3 class='text-center'>Ticket Details</h3>

  <div class="row justify-content-md-center my-2">
    {% if messages %}
      {% for message in messages %}
          <div class="fw-semibold alert alert-{{message.extra_tags}}">{{message}}</div>
      {% endfor %}
    {% endif %}
  </div>

  <div class="my-2">
    <div class="row">
      <div class="col-4">Ticket Reference Number : </div>
      <div class="col-8">{{ticket_data.ticket_reference_number}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket title : </div>
      <div class="col-8">{{ticket_data.ticket_title}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket Description : </div>
      <div class="col-8">{{ticket_data.ticket_desc}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">User Upload Doc : </div>
      <div class="col-8">
        {% if ticket_data.ticket_user_uploaded_document != '' %}
            <a style="text-decoration: none;color:black" href="/media/{{ticket_data.ticket_user_uploaded_document}}" download>
                <div class="tools-section-button fw-bold text-danger">Download</div>
            </a> 
        {% else %}
            -
        {% endif %}
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket Status : </div>
      <div class="col-8">{{ticket_data.ticket_status.status}}
        {% if ticket_data.ticket_status.status == 'escalated' %}
        <span class="ml-3"><a href="{% url 'TicketUser:admin_action' ticket_data.id %}">Reassign Ticket</a></span>{% endif %}
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Website URL : </div>
      <div class="col-8">{{ticket_data.organization_website_url}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Related Area : </div>
      <div class="col-8">{{ticket_data.ticket_related_area}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Technology Stack : </div>
      <div class="col-8">
        {% for data in ticket_data.ticket_technology_stack.all %}
        {{ data.Technology_Stack_Name }}{% if ticket_data.ticket_technology_stack.all|length > forloop.counter %}, {% endif %}
        {% endfor %}
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Technical person email : </div>
      <div class="col-8">{{ticket_data.technical_person_email}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Technical person contact number : </div>
      <div class="col-8">{{ticket_data.technical_person_contact_number}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Admin to agent remark : </div>
      <div class="col-8">{% if admin_action.admin_to_agent_remark %}{{admin_action.admin_to_agent_remark}}{% else %} - {% endif %}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket creation date : </div>
      <div class="col-8">{{ticket_data.ticket_created_date}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket updation date : </div>
      <div class="col-8">{{ticket_data.ticket_user_last_updated_date}}</div>
    </div>
    <hr>

    

    <h3 class="text-center">View conversation</h3>
    {% for d in data %}
    {% if d.agent_resp.agent_action.status == 'attending' %} 

    <div class='bg-warning-subtle'>
      Agent Attended Ticket on  {{d.agent_resp.agent_ticket_action_date}} 
      <br>
    </div>
    
    {% else %}
    <div>
      <h4>agent response</h4>
      agent  : {{d.agent_action.agent_id.user_id.username}}
      <br>
      agent remark : {{d.agent_resp.agent_to_user_remark}}
      <br>
      agent uploaded doc : {{d.agent_resp.agent_ticket_upload_document}}
      <br>
      agent status : {{d.agent_action.agent_action}}
      <br>
      {% if d.user_resp %}
      <h4>user response</h4>
      user remark : {{d.user_resp.user_ticket_reopen_data_description}}
      <br>
      user doc : {{d.user_resp.user_ticket_reopen_docs}}
      <br>
      user status : {{d.user_resp.user_ticket_action_on_agent_response}}
      {% endif %}
    </div>
    <hr>
    {% endif %}
    {% endfor %}


  </div>
</div>

{% endblock %}

TicketUser/templates/TicketUser/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Ticket System</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href='#'>Ticket System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'TicketUser:user_login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
            <span class="mx-2"><a href="{% url 'TicketUser:user_logout' %}">Logout</a></span>
            <span class="mx-2 text-warning">{{request.user}}</span>
          {% endif %}
        </div>
      </div>
    </nav>

</body>

TicketUser/templates/TicketUser/home.html
{% extends 'TicketUser/base.html' %}

{% block home %}
home
{% endblock %}

TicketUser/templates/TicketUser/user_dashboard.html
{% extends 'TicketUser/base.html' %}

{% block user_dashboard %}

<div>
  <h3 class='text-senter mt-4'>Ticket List</h3>

  <span class="mx-2"><a class="btn btn-primary" href="{% url 'TicketUser:create_ticket' %}">Create Ticket</a></span>
    
  <table class="table">
    <thead>
      <tr>
        <th scope="col">s.No.</th>
        <th scope="col">Ticket Number</th>
        <th scope="col">Ticket title</th>
        <th scope="col">Ticket Status</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for d in data %}
      <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{d.ticket_reference_number}}</td>
        <td>{{d.ticket_title}}</td>
        <td>{{d.ticket_status}}</td>
        <td><a href="{% url 'TicketUser:user_view_ticket' d.id %}">View Ticket</a></td>

        
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

TicketUser/templates/TicketUser/user_view_ticket.html
{% extends 'TicketUser/base.html' %}

{% block user_view_ticket %}

<div class="my-3">
  <h3 class='text-center'>Ticket Details</h3>
  
  <div class="row justify-content-md-center my-2">
    {% if messages %}
      {% for message in messages %}
          <div class="fw-semibold alert alert-{{message.extra_tags}}">{{message}}</div>
      {% endfor %}
    {% endif %}
  </div>

  <div class="my-2">
    <div class="row">
      <div class="col-4">Ticket Reference Number : </div>
      <div class="col-8">{{ticket_data.ticket_reference_number}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket title : </div>
      <div class="col-8">{{ticket_data.ticket_title}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket Description : </div>
      <div class="col-8">{{ticket_data.ticket_desc}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">User Upload Doc : </div>
      <div class="col-8">
        {% if ticket_data.ticket_user_uploaded_document != '' %}
            <a style="text-decoration: none;color:black" href="/media/{{ticket_data.ticket_user_uploaded_document}}" download>
                <div class="tools-section-button fw-bold text-danger">Download</div>
            </a> 
        {% else %}
            -
        {% endif %}
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket Status : </div>
      {% comment %} <div class="col-8">{{ticket_data.ticket_status.status}}</div> {% endcomment %}
      {% if ticket_data.ticket_status.status == 'assigned' or ticket_data.ticket_status.status == 'attending' or ticket_data.ticket_status.status == 'open' %}
          <div class="col-8">Inprocess</div>
          {% else %}
          <div class="col-8">{{ticket_data.ticket_status.status}}</div>
        {% endif %}
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Website URL : </div>
      <div class="col-8">{{ticket_data.organization_website_url}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Related Area : </div>
      <div class="col-8">{{ticket_data.ticket_related_area}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Technology Stack : </div>
      <div class="col-8">
        {% for data in ticket_data.ticket_technology_stack.all %}
        {{ data.Technology_Stack_Name }}{% if ticket_data.ticket_technology_stack.all|length > forloop.counter %}, {% endif %}
        {% endfor %}
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Technical person email : </div>
      <div class="col-8">{{ticket_data.technical_person_email}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Technical person contact number : </div>
      <div class="col-8">{{ticket_data.technical_person_contact_number}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket creation date : </div>
      <div class="col-8">{{ticket_data.ticket_created_date}}</div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">Ticket updation date : </div>
      <div class="col-8">{{ticket_data.ticket_user_last_updated_date}}</div>
    </div>
    <hr>


    <h3 class="text-center">View conversation</h3>
    {% for d in data %}

    {% if d.agent_resp.agent_action.status == 'attending' %} 

    <div class='bg-warning-subtle'>
      Agent Attended Ticket on  {{d.agent_resp.agent_ticket_action_date}} 
      <br>
    </div>
    
    {% else %}
    <div>
      <h4>agent response</h4>
      agent : {{d.agent_action.agent_id.user_id.username}}
      <br>
      agent remark : {{d.agent_resp.agent_to_user_remark}}
      <br>
      agent uploaded doc : {{d.agent_resp.agent_ticket_upload_document}}
      <br>
      agent status : {{d.agent_action.agent_action}}
      <br>
      {% if d.user_resp %}
      <h4>user response</h4>
      user remark : {{d.user_resp.user_ticket_reopen_data_description}}
      <br>
      user doc : {{d.user_resp.user_ticket_reopen_docs}}
      <br>
      user status : {{d.user_resp.user_ticket_action_on_agent_response}}
      {% endif %}
    </div>
    <hr>
    {% endif %}
    {% endfor %}

    {% if ticket_data.ticket_status.status == 'insufficient data' or ticket_data.ticket_status.status == 'resolved' %}
    <a href="{% url 'TicketUser:reopen' ticket_data.id %}">Reopen</a>
    {% endif %}
    {% if ticket_data.ticket_status.status == 'resolved' %}
    <a href="{% url 'TicketUser:close_ticket' ticket_data.id %}">Close Ticket</a>
    {% endif %}
  </div>
</div>

{% endblock %}